' Archimate-Sprites
' 07/26/2024 - Splitting off Archimate Sprites to its own extension file to better manage custom sprites

' Sprites
!define ARCHIMATECUSTOMICONURL https://raw.githubusercontent.com/telus/adg-plantuml-common/master/icons/ArchiMate
!includeurl ARCHIMATECUSTOMICONURL/application-module.puml
!includeurl ARCHIMATECUSTOMICONURL/application-system.puml
!includeurl ARCHIMATECUSTOMICONURL/technology-artifact-module.puml
!includeurl ARCHIMATECUSTOMICONURL/technology-node-weblogic.puml
!includeurl ARCHIMATECUSTOMICONURL/technology-node-repository-github.puml