' Archimate-PlantUML
' 12/22/2023 - Updated to enable all ArchiMate elements and rename them to support TELUS metadata.  See https://docs.google.com/spreadsheets/d/1hHAGzGV0kXPZ9gyfa2rFEvY0EBOViG3wsp31FfbIRIY/edit#gid=652489814
' 07/25/2024 - Changed Association arrow from `==` to `-\\`.  The arrow should be `-//` instead but a but is preventing the bottom half arrow type from displaying.  Issue opened with PlantUML: https://github.com/plantuml/plantuml/issues/1867
' 07/26/2024 - Separate out ArchiMate sprites to its own file Archimate_sprites.puml

' TELUS extension styling
skinparam rectangle<<behavior>> {
  roundCorner 0
}

skinparam linetype ortho
skinparam pathHoverColor red
skinparam noteTextAlignment left
skinparam sequenceArrowThickness 0.5

left to right direction
    
sprite $aComponent jar:archimate/application-component
sprite $aDataObject jar:archimate/application-data-object
sprite $aInterface jar:archimate/application-interface
sprite $aService jar:archimate/application-service
sprite $tNetwork jar:archimate/technology-communication-network
sprite $tArtifact jar:archimate/technology-artifact
sprite $tRepository jar:archimate/technology-node
sprite $tNode jar:archimate/technology-node
sprite $tInfraInterface jar:archimate/technology-interface
sprite $bActor jar:archimate/business-actor
sprite $bProcess jar:archimate/business-process

skinparam defaultFontName Arial
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 0.5
skinparam titleFontSize 30
skinparam titleFontColor #4B286D
skinparam footerFontSize 13
skinparam svgLinkTarget _blank
skinparam NoteBorderThickness 0 
skinparam NoteBorderColor #ffffff

<style>
title {
  padding 30 30 30 30
}

package {
  LineColor #71757B
  Color #4B286D
}

note {
  BackgroundColor #ffffff
  BorderColor #ffffff
}
</style>

' Styling
' ##################################
!define TECHN_FONT_SIZE 12
!define ELEMENT_FONT_COLOR #FFFFFF

skinparam defaultTextAlignment center
skinparam wrapWidth 400
skinparam maxMessageSize 150
skinparam StereotypeAlignment right

skinparam Arrow {
    Color #000000
    FontColor #000000
    FontSize 12
}
skinparam rectangle<<grouping>> {
    roundCorner 25
    StereotypeFontSize 0
    FontColor #000000
    BorderColor #444444
}
skinparam Folder<<group>> {
    Shadowing true
    StereotypeFontSize 0
    FontColor #444444
    BackgroundColor lightgrey
}
skinparam rectangle<<boundary>> {
    Shadowing false
    StereotypeFontSize 0
    FontColor #444444
    BorderColor #444444
    BorderStyle dashed
}
skinparam node {
  StereotypeAlignment right
}
skinparam cloud {
  StereotypeAlignment right
}
skinparam frame {
  StereotypeAlignment right
}
skinparam archimate {
  StereotypeAlignment right
  RoundCorner<<strategy-capability>> 25
  RoundCorner<<strategy-course-of-action>> 25
  RoundCorner<<strategy-value-stream>> 25
  RoundCorner<<business-process>> 25
  RoundCorner<<business-event>> 25
  RoundCorner<<business-function>> 25
  RoundCorner<<business-interaction>> 25
  RoundCorner<<business-event>> 25
  RoundCorner<<business-service>> 25
  RoundCorner<<application-function>> 25
  RoundCorner<<application-interaction>> 25
  RoundCorner<<application-process>> 25
  RoundCorner<<application-event>> 25
  RoundCorner<<application-service>> 25
  RoundCorner<<technology-function>> 25
  RoundCorner<<technology-process>> 25
  RoundCorner<<technology-interaction>> 25
  RoundCorner<<technology-event>> 25
  RoundCorner<<technology-infra-service>> 25
  RoundCorner<<implementation-workpackage>> 25
  RoundCorner<<implementation-event>> 25
  DiagonalCorner<<motivation-stakeholder>> 12
  DiagonalCorner<<motivation-driver>> 12
  DiagonalCorner<<motivation-assessment>> 12
  DiagonalCorner<<motivation-goal>> 12
  DiagonalCorner<<motivation-outcome>> 12
  DiagonalCorner<<motivation-principle>> 12
  DiagonalCorner<<motivation-requirement>> 12
  DiagonalCorner<<motivation-constraint>> 12
}
skinparam usecase {
  BorderColor #000000
}

' Custom ArchiMate Extensions
' ##################################
skinparam rectangle<<application-service>> {
    roundCorner 25
  }

skinparam rectangle<<application-system>> {
    'FontSize 20
    'FontName FONTSERIF
    'FontStyle plain
    FontColor blue
    'BorderColor red
    'HyperlinkUnderline true
  }

skinparam rectangle<<code-repository>> {
    'FontSize 20
    'FontName FONTSERIF
    'FontStyle plain
    FontColor black
    'BorderColor red
    'HyperlinkUnderline true
  }

skinparam rectangle<<application-module>> {
    'FontSize 20
    'FontName FONTSERIF
    'FontStyle plain
    'FontColor red
    'BorderColor red
  }

skinparam rectangle<<technology-artifact-module>> {
    'FontSize 20
    'FontName FONTSERIF
    'FontStyle plain
    'FontColor red
    'BorderColor red
  }

skinparam rectangle<<technology-node-weblogic>> {
    'FontSize 20
    'FontName FONTSERIF
    'FontStyle plain
    'FontColor red
    'BorderColor red
  }

' Layout
' ##################################
!definelong LAYOUT_AS_SKETCH
    skinparam backgroundColor #EEEBDC
    skinparam handwritten true
    skinparam defaultFontName "Comic Sans MS"
    center footer <font color=red>Warning:</font> Created for discussion, needs to be validated
!enddefinelong
!define LAYOUT_TOP_DOWN top to bottom direction
!define LAYOUT_LEFT_RIGHT left to right direction

' Layout Helpers
' ##################################
!define Lay_D(e_from, e_to) e_from -[hidden]D- e_to
!define Lay_U(e_from, e_to) e_from -[hidden]U- e_to
!define Lay_R(e_from, e_to) e_from -[hidden]R- e_to
!define Lay_L(e_from, e_to) e_from -[hidden]L- e_to

' Boundaries
' ##################################
!define Boundary(e_alias, e_label) rectangle "==e_label" <<boundary>> as e_alias
!define Boundary(e_alias, e_label, e_type) rectangle "==e_label\n<size:TECHN_FONT_SIZE>[e_type]</size>" <<boundary>> as e_alias

' Elements
' ##################################
' TELUS element custom extensions - 7/20/2023
' THESE ELEMENTS ARE LINKABLE
!define ApplicationComponent(e_alias, e_label, e_link) rectangle "e_label" <<$aComponent>><<application-component>> as e_alias [[e_link]] #Application
!define ApplicationInterface(e_alias, e_label, e_link) rectangle "e_label" <<$aInterface>><<application-interface>> as e_alias [[e_link]] #Application
!define ApplicationSystem(e_alias, e_label, e_link) rectangle "e_label" <<$aSystem>><<application-system>> as e_alias [[e_link]] #Application
!define ApplicationModule(e_alias, e_label, e_link) rectangle "e_label" <<$aModule>><<application-module>> as e_alias [[e_link]] #Application
!define Application_System(e_alias, e_label, e_link) rectangle "e_label" <<$aSystem>><<application-system>> as e_alias [[e_link]] #Application
!define Application_Module(e_alias, e_label, e_link) rectangle "e_label" <<$aModule>><<application-module>> as e_alias [[e_link]] #Application
!define DataObject(e_alias, e_label, e_link) rectangle "e_label" <<$aDataObject>><<application-data-object>> as e_alias [[e_link]] #Application
!define Artifact(e_alias, e_label, e_link)  rectangle "e_label" <<$tArtifact>><<technology-artifact>> as e_alias [[e_link]] #Technology
!define Node(e_alias, e_label, e_link)  rectangle "e_label" <<$tNode>><<technology-node>> as e_alias [[e_link]] #Technology
!define Technology_Node_Weblogic(e_alias, e_label, e_link) node #TECHNOLOGY "e_label" <<$tNodeWeblogic>><<technology-node-weblogic>> as e_alias [[e_link]] 
!define Node_Repository_GitHub(e_alias, e_label, e_link) node #TECHNOLOGY "e_label" <<$tNodeRepositoryGitHub>><<technology-node-repository-github>> as e_alias [[e_link]] 
!define CodeRepository(e_alias, e_label, e_link) rectangle "e_label" <<$tArtifact>><<code-repository>> as e_alias [[e_link]] #lightgreen
!define CommunicationNetwork(e_alias, e_label, e_link)  rectangle "e_label" <<$tNetwork>><<technology-network>> as e_alias [[e_link]] #Technology
!define BusinessActor(e_alias, e_label, e_link) rectangle #BUSINESS "e_label" <<$bActor>><<business-actor>> as e_alias [[e_link]]

' UPDATING THE BELOW ELEMENTS BY REMOVING THE '_' SPACING TO ENABLE IN PLANTUML - 12/22/2023
'Strategy Elements
!define Resource(e_alias, e_label, e_link) archimate #STRATEGY "....\n e_label" <<strategy-resource>> as e_alias [[e_link]]
!define Capability(e_alias, e_label, e_link) archimate #STRATEGY "e_label" <<strategy-capability>> as e_alias [[e_link]]
!define CourseOfAction(e_alias, e_label, e_link) archimate #STRATEGY "e_label" <<strategy-course-of-action>> as e_alias [[e_link]]
!define ValueStream(e_alias, e_label, e_link) archimate #STRATEGY "e_label" <<strategy-value-stream>> as e_alias [[e_link]]

'Business Elements
'!define BusinessActor(e_alias, e_label) archimate #BUSINESS "e_label" <<business-actor>> as e_alias
!define BusinessRole(e_alias, e_label, e_link) archimate #BUSINESS "e_label" <<business-role>> as e_alias [[e_link]]
!define BusinessCollaboration(e_alias, e_label, e_link) archimate #BUSINESS "e_label" <<business-collaboration>> as e_alias [[e_link]]
!define BusinessInterface(e_alias, e_label, e_link) archimate #BUSINESS "e_label" <<business-interface>> as e_alias [[e_link]]
!define BusinessProcess(e_alias, e_label, e_link) rectangle #BUSINESS "e_label" <<$bProcess>><<business-process>> as e_alias [[e_link]]
!define BusinessFunction(e_alias, e_label, e_link) archimate #BUSINESS "e_label" <<business-function>> as e_alias [[e_link]]
!define BusinessInteraction(e_alias, e_label, e_link) archimate #BUSINESS "e_label" <<business-interaction>> as e_alias [[e_link]]
!define BusinessEvent(e_alias, e_label, e_link) archimate #BUSINESS "e_label" <<business-event>> as e_alias [[e_link]]
!define BusinessService(e_alias, e_label, e_link) archimate #BUSINESS "e_label" <<business-service>> as e_alias [[e_link]]
!define BusinessObject(e_alias, e_label, e_link) archimate #BUSINESS "----\n e_label" <<business-object>> as e_alias [[e_link]]
!define BusinessContract(e_alias, e_label, e_link) archimate #BUSINESS "----\n e_label\n----" <<business-contract>> as e_alias [[e_link]]
!define BusinessRepresentation(e_alias, e_label, e_link) archimate #BUSINESS "----\n e_label" <<business-representation>> as e_alias [[e_link]]
!define BusinessProduct(e_alias, e_label, e_link) archimate #BUSINESS "e_label" <<business-product>> as e_alias [[e_link]]
!define BusinessLocation(e_alias, e_label, e_link) archimate #BUSINESS "e_label" <<business-location>> as e_alias [[e_link]]

'Application Elements
'!define ApplicationComponent(e_alias, e_label) archimate #APPLICATION "e_label" <<application-component>> as e_alias
!define ApplicationCollaboration(e_alias, e_label, e_link) archimate #APPLICATION "e_label" <<application-collaboration>> as e_alias [[e_link]]
'!define ApplicationInterface(e_alias, e_label) archimate #APPLICATION "e_label" <<application-interface>> as e_alias
!define ApplicationFunction(e_alias, e_label, e_link) archimate #APPLICATION "e_label" <<application-function>> as e_alias [[e_link]]
!define ApplicationInteraction(e_alias, e_label, e_link) archimate #APPLICATION "e_label" <<application-interaction>> as e_alias [[e_link]]
!define ApplicationProcess(e_alias, e_labe, e_linkl) archimate #APPLICATION "e_label" <<application-process>> as e_alias [[e_link]]
!define ApplicationEvent(e_alias, e_label, e_link) archimate #APPLICATION "e_label" <<application-event>> as e_alias [[e_link]]
!define ApplicationService(e_alias, e_label, e_link) rectangle "e_label" <<$aService>><<application-service>> as e_alias [[e_link]] #lightgrey
'!define ApplicationDataObject(e_alias, e_label) archimate #APPLICATION "e_label" <<application-data-object>> as e_alias

'Technology Elements
'!define Technology_Node(e_alias, e_label) node #TECHNOLOGY "e_label" <<$archimate/technology-node>> as e_alias
!define Device(e_alias, e_label, e_link) node #TECHNOLOGY "e_label" <<$archimate/technology-device>> as e_alias [[e_link]]
!define SystemSoftware(e_alias, e_label, e_link) archimate #TECHNOLOGY "e_label" <<technology-system-software>> as e_alias [[e_link]]
!define TechnologyCollaboration(e_alias, e_label, e_link) archimate #TECHNOLOGY "e_label" <<technology-collaboration>> as e_alias [[e_link]]
!define TechnologyInterface(e_alias, e_label, e_link) archimate #TECHNOLOGY "e_label" <<technology-infra-interface>> as e_alias [[e_link]]
!define Path(e_alias, e_label, e_link) archimate #TECHNOLOGY "e_label" <<technology-communication-path>> as e_alias [[e_link]]
'!define Technology_CommunicationNetwork(e_alias, e_label) archimate #TECHNOLOGY "e_label" <<technology-network>> as e_alias
!define TechnologyFunction(e_alias, e_label, e_link) archimate #TECHNOLOGY "e_label" <<technology-function>> as e_alias [[e_link]]
!define TechnologyProcess(e_alias, e_label, e_link) archimate #TECHNOLOGY "e_label" <<technology-process>> as e_alias [[e_link]]
!define TechnologyInteraction(e_alias, e_label, e_link) archimate #TECHNOLOGY "e_label" <<technology-interaction>> as e_alias [[e_link]]
!define TechnologyEvent(e_alias, e_label, e_link) archimate #TECHNOLOGY "e_label" <<technology-event>> as e_alias [[e_link]]
!define TechnologyService(e_alias, e_label, e_link) archimate #TECHNOLOGY "e_label" <<technology-infra-service>> as e_alias [[e_link]]
'!define Technology_Artifact(e_alias, e_label) archimate #TECHNOLOGY "e_label" <<technology-artifact>> as e_alias
!define ArtifactModule(e_alias, e_label, e_link) archimate #TECHNOLOGY "e_label" <<technology-artifact-module>> as e_alias [[e_link]]

'Physical Elements
!define Equipment(e_alias, e_label, e_link) node #PHYSICAL "e_label" <<$archimate/physical-equipment>> as e_alias [[e_link]]
!define Facility(e_alias, e_label, e_link) node #PHYSICAL "e_label" <<$archimate/physical-facility>> as e_alias [[e_link]]
!define DistributionNetwork(e_alias, e_label, e_link) archimate #PHYSICAL "e_label" <<physical-distribution-network>> as e_alias [[e_link]]
!define Material(e_alias, e_label, e_link) archimate #PHYSICAL "----\n e_label" <<physical-material>> as e_alias [[e_link]]

'Motivation Elements
!define Stakeholder(e_alias, e_label, e_link) archimate #MOTIVATION "e_label" <<motivation-stakeholder>> as e_alias [[e_link]]
!define Driver(e_alias, e_label, e_link) archimate #MOTIVATION "e_label" <<motivation-driver>> as e_alias [[e_link]]
!define Assessment(e_alias, e_label, e_link) archimate #MOTIVATION "e_label" <<motivation-assessment>> as e_alias [[e_link]]
!define Goal(e_alias, e_label, e_link) archimate #MOTIVATION "e_label" <<motivation-goal>> as e_alias [[e_link]]
!define Outcome(e_alias, e_labe, e_linkl) archimate #MOTIVATION "e_label" <<motivation-outcome>> as e_alias [[e_link]]
!define Principle(e_alias, e_label, e_link) archimate #MOTIVATION "e_label" <<motivation-principle>> as e_alias [[e_link]]
!define Requirement(e_alias, e_label, e_link) archimate #MOTIVATION "e_label" <<motivation-requirement>> as e_alias [[e_link]]
!define Constraint(e_alias, e_label, e_link) archimate #MOTIVATION "e_label" <<motivation-constraint>> as e_alias [[e_link]]
!define Meaning(e_alias, e_label, e_link) cloud #MOTIVATION "e_label" <<$archimate/motivation-meaning>> as e_alias [[e_link]]
!define Value(e_alias, e_label, e_link) usecase #MOTIVATION "e_label" as e_alias [[e_link]]

'Implementation Elements
!define WorkPackage(e_alias, e_label, e_link) archimate #IMPLEMENTATION "e_label" <<implementation-workpackage>> as e_alias [[e_link]]
!define Deliverable(e_alias, e_label, e_link) archimate #IMPLEMENTATION "----\n e_label" <<implementation-deliverable>> as e_alias [[e_link]]
!define ImplementationEvent(e_alias, e_label, e_link) archimate #IMPLEMENTATION "e_label" <<implementation-event>> as e_alias [[e_link]]
!define Plateau(e_alias, e_label, e_link) node #PHYSICAL "e_label" <<$archimate/implementation-plateau>> as e_alias [[e_link]]
!define Gap(e_alias, e_label, e_link) archimate #PHYSICAL "----\n e_label" <<implementation-gap>> as e_alias [[e_link]]

'Other Elements
!define Other_Location(e_alias, e_label, e_link) archimate #ffb973 "e_label" <<location>> as e_alias [[e_link]]
!define Junction_Or(e_alias, e_label, e_link) circle #whitesmoke "e_label" as e_alias [[e_link]]
!define Junction_And(e_alias, e_label, e_link) circle #black "e_label" as e_alias [[e_link]]
!define Grouping(e_alias, e_label, e_link) rectangle "e_label" <<$aService>><<grouping>> as e_alias [[e_link]] #lightgrey
!define Group(e_alias, e_label, e_link) Folder "e_label" <<group>> as e_alias [[e_link]]

' Custom (Derived) Relationships
' Dervived Relationships will have a lighter line and text colour [#eee]
!define Rel_Composition_Derived(e_From, e_To, e_label="") Rel_(e_From, e_To, <color:#bbb>e_label, "*-[#bbb]-")
!define Rel_Aggregation_Derived(e_From, e_To, e_label="") Rel_(e_From, e_To, <color:#bbb>e_label, "o-[#bbb]-")
!define Rel_Assignment_Derived(e_From, e_To, e_label="") Rel_(e_From, e_To, <color:#bbb>e_label, "@-[#bbb]->>")
!define Rel_Specialization_Derived(e_From, e_To, e_label="") Rel_(e_From, e_To, <color:#bbb>e_label, "-[#bbb]-|>")
!define Rel_Serving_Derived(e_From, e_To, e_label="") Rel_(e_From, e_To, <color:#bbb>e_label, "-[#bbb]->")
!define Rel_Association_Derived(e_From, e_To, e_label="") Rel_(e_From, e_To, <color:#bbb>e_label, "=[#bbb]=")
!define Rel_Flow_Derived(e_From, e_To, e_label="") Rel_(e_From, e_To, <color:#bbb>e_label, ".[#bbb].>>")
!define Rel_Realization_Derived(e_From, e_To, e_label="") Rel_(e_From, e_To, <color:#bbb>e_label, "~[#bbb]~|>")
!define Rel_Triggering_Derived(e_From, e_To, e_label="") Rel_(e_From, e_To, <color:#bbb>e_label, "-[#bbb]->>")
!define Rel_Access_Derived(e_From, e_To, e_label="") Rel_(e_From, e_To, <color:#bbb>e_label, "~[#bbb]~")
!define Rel_Influence_Derived(e_From, e_To, e_label="") Rel_(e_From, e_To, <color:#bbb>e_label, ".[#bbb].>")


' Relationships
' ##################################
!define Rel_(e_sourceAlias, e_targetAlias, e_label, e_direction="") e_sourceAlias e_direction e_targetAlias : "e_label"

!define Rel_Composition(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "*--")
!define Rel_Composition_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "*-UP-")
!define Rel_Composition_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "*-DOWN-")
!define Rel_Composition_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "*-LEFT-")
!define Rel_Composition_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "*-RIGHT-")

!define Rel_Aggregation(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "o--")
!define Rel_Aggregation_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "o-UP-")
!define Rel_Aggregation_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "o-DOWN-")
!define Rel_Aggregation_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "o-LEFT-")
!define Rel_Aggregation_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "o-RIGHT-")

!define Rel_Assignment(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "@-->>")
!define Rel_Assignment_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "@-UP->>")
!define Rel_Assignment_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "@-DOWN->>")
!define Rel_Assignment_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "@-LEFT->>")
!define Rel_Assignment_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "@-RIGHT->>")

!define Rel_Specialization(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "--|>")
!define Rel_Specialization_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-UP-|>")
!define Rel_Specialization_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-DOWN-|>")
!define Rel_Specialization_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-LEFT-|>")
!define Rel_Specialization_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-RIGHT-|>")

!define Rel_Serving(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-->")
!define Rel_Serving_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-UP->")
!define Rel_Serving_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-DOWN->")
!define Rel_Serving_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-LEFT->")
!define Rel_Serving_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-RIGHT->")

!define Rel_Association(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-\\")
!define Rel_Association_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-UP-\\")
!define Rel_Association_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-DOWN-\\")
!define Rel_Association_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-LEFT-\\")
!define Rel_Association_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-RIGHT-\\")

!define Rel_Flow(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "..>>")
!define Rel_Flow_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, ".UP.>>")
!define Rel_Flow_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, ".DOWN.>>")
!define Rel_Flow_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, ".LEFT.>>")
!define Rel_Flow_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, ".RIGHT.>>")

!define Rel_Realization(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~~|>")
!define Rel_Realization_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~UP~|>")
!define Rel_Realization_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~DOWN~|>")
!define Rel_Realization_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~LEFT~|>")
!define Rel_Realization_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~RIGHT~|>")

!define Rel_Triggering(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-->>")
!define Rel_Triggering_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-UP->>")
!define Rel_Triggering_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-DOWN->>")
!define Rel_Triggering_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-LEFT->>")
!define Rel_Triggering_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-RIGHT->>")

!define Rel_Access(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~~")
!define Rel_Access_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~UP~")
!define Rel_Access_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~DOWN~")
!define Rel_Access_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~LEFT~")
!define Rel_Access_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~RIGHT~")

!define Rel_Access_r(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "<-~")
!define Rel_Access_r_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "<-UP~")
!define Rel_Access_r_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "<-DOWN~")
!define Rel_Access_r_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "<-LEFT~")
!define Rel_Access_r_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "<-RIGHT~")

!define Rel_Access_rw(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "<~~>")
!define Rel_Access_rw_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "<~UP~>")
!define Rel_Access_rw_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "<~DOWN~>")
!define Rel_Access_rw_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "<~LEFT~>")
!define Rel_Access_rw_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "<~RIGHT~>")

!define Rel_Access_w(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~->")
!define Rel_Access_w_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~UP->")
!define Rel_Access_w_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~DOWN->")
!define Rel_Access_w_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~LEFT->")
!define Rel_Access_w_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "~RIGHT->")

!define Rel_Influence(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "..>")
!define Rel_Influence_Up(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, ".UP.>")
!define Rel_Influence_Down(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, ".DOWN.>")
!define Rel_Influence_Left(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, ".LEFT.>")
!define Rel_Influence_Right(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, ".RIGHT.>")
